name       : haskell-fixed
version    : 0.2.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/fixed-0.2.1.1/fixed-0.2.1.1.tar.gz : 24a9e1e251998c9d06037bb771d9eab2980a91132de59a19d0166a1c51e715e2
license    : BSD-3-Clause
component  : programming
summary    : Signed 15.16 precision fixed point arithmetic
description: |
    Signed 15.16 precision fixed point arithmetic
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 fixed-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/fixed-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/fixed-$version/*.a
