name       : haskell-fixed
version    : '0.3'
release    : 5
source     :
    - https://hackage.haskell.org/package/fixed-0.3/fixed-0.3.tar.gz : 9218ebd3af3f07335db8dcd148b3ce40acf984734c244cce5959f57402d48282
license    : BSD-3-Clause
component  : programming.haskell
summary    : Signed 15.16 precision fixed point arithmetic
description: |
    Signed 15.16 precision fixed point arithmetic
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
