name       : haskell-fixed
version    : 0.2.1.1
release    : 4
source     :
    - http://hackage.haskell.org/package/fixed-0.2.1.1/fixed-0.2.1.1.tar.gz : 24a9e1e251998c9d06037bb771d9eab2980a91132de59a19d0166a1c51e715e2
license    : BSD-3-Clause
component  : programming.haskell
summary    : Signed 15.16 precision fixed point arithmetic
description: |
    Signed 15.16 precision fixed point arithmetic
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
